apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: externalsecrets-sa
            namespace: security
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: externalsecrets-sa
  namespace: security
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/eso-role
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: airflow-connections
  namespace: data
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: airflow-connections
  data:
    - secretKey: AIRFLOW_CONN_SNOWFLAKE
      remoteRef:
        key: airflow/connections/snowflake
    - secretKey: AIRFLOW_CONN_DATABRICKS
      remoteRef:
        key: airflow/connections/databricks


