# External Secrets para Airbyte
# Sincroniza credenciales desde AWS Secrets Manager / Azure Key Vault / HashiCorp Vault

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: airbyte-credentials
  namespace: integration
spec:
  secretStoreRef:
    name: aws-secrets-manager  # Cambiar a azure-key-vault o vault si aplica
    kind: SecretStore
  target:
    name: airbyte-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        # Credenciales de API de Airbyte
        airbyte-password: "{{ .airbyte_password }}"
        # Credenciales de PostgreSQL interno
        postgres-password: "{{ .postgres_password }}"
        # Credenciales de MinIO (si se usa)
        minio-password: "{{ .minio_password }}"
  data:
    # Password para autenticación en Airbyte
    - secretKey: airbyte_password
      remoteRef:
        key: airbyte/api-password  # Path en Secrets Manager/Key Vault
    # Password de PostgreSQL para Airbyte
    - secretKey: postgres_password
      remoteRef:
        key: airbyte/postgres-password
    # Password de MinIO para Airbyte
    - secretKey: minio_password
      remoteRef:
        key: airbyte/minio-password

---
# External Secret para credenciales de Airflow (acceso a Airbyte API)
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: airbyte-airflow-credentials
  namespace: data
spec:
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: airbyte-airflow-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        # Variables para Airflow
        AIRBYTE_API_URL: "http://airbyte-server.integration.svc.cluster.local:8000"
        AIRBYTE_API_USERNAME: "airbyte"
        AIRBYTE_API_PASSWORD: "{{ .airbyte_password }}"
  data:
    - secretKey: airbyte_password
      remoteRef:
        key: airbyte/api-password





