apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: airflow-notifications
  namespace: data
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: airflow-secrets
  data:
    - secretKey: slack-webhook-url
      remoteRef:
        key: airflow/notifications/slack_webhook_url
    - secretKey: alert-emails
      remoteRef:
        key: airflow/notifications/alert_emails
    - secretKey: sentry-dsn
      remoteRef:
        key: airflow/notifications/sentry_dsn
