apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault
spec:
  provider:
    azurekv:
      tenantId: 00000000-0000-0000-0000-000000000000
      vaultUrl: https://myvault.vault.azure.net
      authType: WorkloadIdentity
      serviceAccountRef:
        name: externalsecrets-sa
        namespace: security
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: externalsecrets-sa
  namespace: security
  annotations:
    azure.workload.identity/client-id: 00000000-0000-0000-0000-000000000000
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: airflow-connections
  namespace: data
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: airflow-connections
  data:
    - secretKey: AIRFLOW_CONN_SNOWFLAKE
      remoteRef:
        key: airflow-connections-snowflake
    - secretKey: AIRFLOW_CONN_DATABRICKS
      remoteRef:
        key: airflow-connections-databricks


