# ServiceMonitor para Camunda - Métricas de procesos BPMN
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: camunda
  namespace: workflows
  labels:
    app: camunda
spec:
  selector:
    matchLabels:
      app: camunda
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s
      scrapeTimeout: 10s


