# ServiceMonitor para Flowable - Métricas de procesos BPMN
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flowable
  namespace: workflows
  labels:
    app: flowable
spec:
  selector:
    matchLabels:
      app: flowable
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s
      scrapeTimeout: 10s


