apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: healthz
  namespace: observability
spec:
  selector:
    matchLabels:
      app: healthz
  namespaceSelector:
    matchNames:
      - integration
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
