domains:
  api: api.example.com
  auth: auth.example.com
  grafana: grafana.example.com
  mlflow: mlflow.example.com
  kibana: kibana.example.com
oidc:
  issuer: https://login.example.com/realms/myrealm
  clientIdSecretRef: oauth2-client-id
  clientSecretSecretRef: oauth2-client-secret
certManager:
  clusterIssuer: letsencrypt-prod
storage:
  s3:
    bucket: biz-datalake-prod
    region: us-east-1

# KPI Thresholds (production - strict)
kpi:
  thresholds:
    leads_critical: 50
    leads_warning: 80
    revenue_vs_avg7d_critical: 0.7  # 70% in prod
    revenue_vs_avg7d_warning: 0.85
    payment_success_critical: 92
    payment_success_warning: 95
  refresh_schedule: "0 */4 * * *"  # Every 4 hours in prod
  dq_health_schedule: "0 */6 * * *"  # Every 6 hours in prod
