# ClusterSecretStore para External Secrets Operator integrado con Vault
# Permite usar Vault como backend para External Secrets
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-secret-store
spec:
  provider:
    vault:
      # URL del servicio de Vault
      server: "http://vault.security.svc.cluster.local:8200"
      # Path del secret engine (kv v2)
      path: "secret"
      version: v2
      # Autenticación mediante Kubernetes Service Account
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets-operator"
          serviceAccountRef:
            name: externalsecrets-vault-sa
            namespace: security
---
# ServiceAccount para External Secrets Operator que se conecta a Vault
apiVersion: v1
kind: ServiceAccount
metadata:
  name: externalsecrets-vault-sa
  namespace: security
---
# ClusterRole y ClusterRoleBinding para que External Secrets pueda leer de Vault
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: externalsecrets-vault-reader
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["serviceaccounts/token"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: externalsecrets-vault-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: externalsecrets-vault-reader
subjects:
  - kind: ServiceAccount
    name: externalsecrets-vault-sa
    namespace: security


