# Ejemplos de External Secrets usando Vault como backend
# Estos secretos se sincronizan automáticamente desde Vault a Kubernetes Secrets

---
# Ejemplo: Token de HubSpot desde Vault
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hubspot-token-vault
  namespace: workflows
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: hubspot-token
    creationPolicy: Owner
  data:
    - secretKey: HUBSPOT_TOKEN
      remoteRef:
        key: crm/hubspot/token
        property: token

---
# Ejemplo: Credenciales de base de datos desde Vault
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: leads-db-creds-vault
  namespace: workflows
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: leads-db-creds
    creationPolicy: Owner
  data:
    - secretKey: JDBC_URL
      remoteRef:
        key: databases/leads/url
        property: url
    - secretKey: JDBC_USER
      remoteRef:
        key: databases/leads/username
        property: username
    - secretKey: JDBC_PASSWORD
      remoteRef:
        key: databases/leads/password
        property: password

---
# Ejemplo: Secretos de Airflow desde Vault
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: airflow-secrets-vault
  namespace: data
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: airflow-secrets
    creationPolicy: Owner
  data:
    - secretKey: slack-webhook-url
      remoteRef:
        key: notifications/slack/webhook
        property: url
    - secretKey: alert-emails
      remoteRef:
        key: notifications/email/alert-list
        property: emails

---
# Ejemplo: OpenAI API Key desde Vault
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openai-api-key-vault
  namespace: workflows
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: openai-api-key
    creationPolicy: Owner
  data:
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: ai/openai/api_key
        property: key

---
# Ejemplo: Credenciales de conexión Airflow (Snowflake, Databricks) desde Vault
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: airflow-connections-vault
  namespace: data
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: airflow-connections
    creationPolicy: Owner
  data:
    - secretKey: AIRFLOW_CONN_SNOWFLAKE
      remoteRef:
        key: airflow/connections/snowflake
        property: uri
    - secretKey: AIRFLOW_CONN_DATABRICKS
      remoteRef:
        key: airflow/connections/databricks
        property: uri


